name = "Greetings!"
uid = "greeting-mod0-blabl-0000-version00001"
version = 1
copyright = "CookieNoob"
description = "Greets other players at the beginning of the game and also congratulates in case of a loss."
author = "CookieNoob"
icon = "/mods/Greetings/hi.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
